config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  resources :users, only: :create

end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :send_email_to_admin

  extend Enumerize

  enumerize :organisation_type, in: [:hotel, :association]

  validates :organisation_type, presence: {message: 'Veuillez choisir un type d\'organisation'}
  validates :first_name,  presence: { message: 'Veuillez remplir votre prénom' }
  validates :last_name,   presence: { message: 'Veuillez remplir votre nom' }
  validates :email,presence: true,  format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: 'Veuillez renseigner un email valide'
  }
private

 def send_email_to_admin
    UserMailer.new_subscription(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.new_subscription(@user).deliver_now
      redirect_to root_path
      flash[:notice] = "Merci pour votre inscription, nous vous tiendrons au courant très vite"
    else
      render "home/show"
    end

  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :telephone,
      :organisation,
      :organisation_type
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<div class="background-cover">
  <div class="row text-center quickbed">
    <div class="text-center">
     <%= image_tag "quickbed_logo.png", class: "base-logo" %>
    </div>
    <p class="punchline">La technologie au service de l'hébergement d’urgence</p>
  </div>
  <div class="row options">
    <div class=" col-sx-12 col-sm-6">
      <div class="card card-block text-center">
        <h3 class="card-title option-title ">Vous êtes un Hotelier</h3>
        <p class="card-text">Par ici si vous souhaitez accueillir des réfugiés.</p>
        <%= link_to "Découvrir la plateforme", "#", class: "btn btn-success btn-lg js-subscription-form" %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card card-block text-center">
        <h3 class="card-title option-title">Vous êtes un Organisme</h3>
        <p class="card-text">Par ici si vous faites parti d'une association aidant les réfugiés à trouver un hébergement.</p>
        <%= link_to "Découvrir la plateforme", "#", class: "btn btn-success btn-lg js-subscription-form" %>
      </div>
    </div>
  </div>
</div>
  <div class="row" id="story">
    <h1 class= "text-center">Pourquoi Quickbed ?</h1>
  </div>

  <div class="row  feature-helper">
    <h2 class="text-center subtitle">Pour les Associations : un service <strong>gratuit</strong></h2>
    <div class="col-sm-4 col-xs-12">
      <div class="text-center">
        <div class="functionnality_desc ">
          <div class="adjust">
            <i class="fa fa-cog fa-5x" aria-hidden="true"></i>
          </div>
          <h3>Simplifiez votre process de placement de résidents</h3>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="text-center">
        <div class="functionnality_desc">
          <i class="fa fa-bed fa-5x" aria-hidden="true"></i>
          <h3>Trouvez des hébergements rapidement et adaptés à vos besoins</h3>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="text-center">
        <div class="functionnality_desc">
          <i class="fa fa-money fa-5x" aria-hidden="true"></i>
          <h3> Gérez, groupez et payez vos factures en quelques clics</h3>
        </div>
      </div>
    </div>
  </div>
  <div class="row feature-host">
    <h2 class="text-center subtitle">Pour les Hoteliers : une solution <strong>optimale</strong></h2>
    <div class="col-sm-4 col-xs-12 text-center">
      <div class="functionnality_desc">
        <i class="fa fa-h-square fa-5x" aria-hidden="true"></i>
        <h3>Optimisation du taux d'occupation de votre hotel</h3>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12 text-center ">
      <div class="functionnality_desc">
        <i class="fa fa-file-pdf-o fa-5x" aria-hidden="true"></i>
        <h3>Gestion automatisée et facile des factures</h3>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12 text-center">
      <div class="functionnality_desc">
        <i class="fa fa-thumb-tack fa-5x" aria-hidden="true"></i>
        <h3>Gestion optimale de vos tâches journalières</h3>
      </div>
    </div>
  </div>
  <div class="row subscribe" id="subscription_form">
    <h1 class="text-center">Soyez premier à tester !</h1>
    <div class="col-sm-offset-4 col-sm-4 col-xs-offset-2 col-xs-8">
      <%= simple_form_for @user, url: users_path do |f| %>
        <%= f.error_notification %>
        <div class="form-group">
          <%= f.input :first_name, label: "Prénom", class: "form-control", placeholder: "Jean"%>
        </div>
        <div class="form-group">
          <%= f.input :last_name, label: "Nom", class: "form-control", placeholder: "Dupond" %>
        </div>
        <div class="form-group">
          <%= f.input :email, label: "Email", class: "form-control", placeholder: "dupond@gmail.com" %>
        </div>
        <div class="form-group">
          <%= f.input :organisation, label: "Société", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.input :organisation_type, label: "Qui êtes vous?", class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Demander une Démo", class: "btn btn-lg btn-primary" %>
          <p>Nous vous rappellerons dans les plus brefs délais</p>
        </div>
      <% end -%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quickbed</title>
  <meta name="google-site-verification" content="43NbU9U_-3wVznl__RFpOpO2x6swimVgoQn_NJarkMA" />
  <meta name="description" content="La technologie au service de l'hébergement d'urgence"/>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta property="og:image" content="http://www.quickbed.org/quickbed_blue_background.png"/>
  <%= render 'shared/favicon'%>
</head>
<body>
  <%= render 'shared/navbar'%>
 <%= render 'shared/flashes' %>

<%= yield %>

</body>
</html>

app/views/shared/_favicon.html.slim
/ Add to homescreen for Chrome on Android
meta name="mobile-web-app-capable" content="yes"
meta name="application-name" content="Quickbed"
link rel="icon" sizes="192x192" href="/chrome-touch-icon-192x192.png"

/ Add to homescreen for Safari on iOS
meta name="apple-mobile-web-app-capable" content="yes"
meta name="apple-mobile-web-app-status-bar-style" content="white"
meta name="apple-mobile-web-app-title" content="Quickbed"
link rel="apple-touch-icon" href="/apple-touch-icon.png"

/ Tile icon for Win8 (144x144 + tile color)
meta name="msapplication-TileImage" content="ms-touch-icon-144x144-precomposed.png"
meta name="msapplication-TileColor" content="#F7F7F7"
meta name="theme-color" content="#F7F7F7"

/ Classic favicons
link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196"
link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160"
link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96"
link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"
link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"

app/views/shared/_flashes.html.slim
- if notice
  div class="alert alert-info alert-dismissible" id="alert" role="alert"
    div class="container"
      div class="row"
        div class="col-xs-12"
          button type="button" class="close" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;
          = notice.html_safe

- if alert
    div class="alert alert-warning alert-dismissible" id="alert" role="alert"
      div class="container"
        div class="row"
          div class="col-xs-12"
            button type="button" class="close" data-dismiss="alert" aria-label="Close"
              span aria-hidden="true" &times;
            = alert.html_safe

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="#" class="navbar-wagon-brand">
    <%= image_tag "quickbed_logo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">




    <!-- Text link -->
    <a href="#" class="navbar-wagon-item navbar-wagon-link js-subscription-form ">Nous Contacter</a>

    <!-- Text link -->
    <a href="#" class="navbar-wagon-item navbar-wagon-link js-scroll-story">Objectifs</a>
  </div>
</div>